# Site settings
title: Abhilash Rathod
author:
  name: Abhilash Rathod
  email: toabhilashrathod@gmail.com



# Build settings
remote_theme: pages-themes/minimal@v0.2.0

header_pages:
  - about.md
  
skin: dark
